default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: db
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
